# Generated by Django 5.0.6 on 2024-07-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_following_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
